# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window3_search.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ChildWindow_3(object):
    def setupUi(self, window3):
        window3.setObjectName("window3")
        window3.resize(594, 364)
        window3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.groupBox = QtWidgets.QGroupBox(window3)
        self.groupBox.setGeometry(QtCore.QRect(20, 20, 551, 321))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 40, 511, 61))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-style:solid\n"
"")
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color: rgb(170, 255, 255)")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(20, 120, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.textEdit = QtWidgets.QTextEdit(self.groupBox)
        self.textEdit.setGeometry(QtCore.QRect(20, 160, 371, 131))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.textEdit.setFont(font)
        self.textEdit.setStyleSheet("border-top-color: rgb(85, 170, 255);\n"
"")
        self.textEdit.setObjectName("textEdit")
        self.line = QtWidgets.QFrame(self.groupBox)
        self.line.setGeometry(QtCore.QRect(20, 90, 511, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.comboBox = QtWidgets.QComboBox(self.groupBox)
        self.comboBox.setGeometry(QtCore.QRect(426, 160, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.labelSource = QtWidgets.QLabel(self.groupBox)
        self.labelSource.setGeometry(QtCore.QRect(410, 120, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelSource.setFont(font)
        self.labelSource.setObjectName("labelSource")
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_3.setGeometry(QtCore.QRect(430, 260, 93, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("background-color: rgb(170, 255, 255)")
        self.pushButton_3.setObjectName("pushButton_3")
        self.layoutWidget.raise_()
        self.label.raise_()
        self.line.raise_()
        self.textEdit.raise_()
        self.comboBox.raise_()
        self.labelSource.raise_()
        self.pushButton_3.raise_()

        self.retranslateUi(window3)
        QtCore.QMetaObject.connectSlotsByName(window3)

    def retranslateUi(self, window2):
        _translate = QtCore.QCoreApplication.translate
        window2.setWindowTitle(_translate("window3", "window3"))
        self.groupBox.setTitle(_translate("window3", "英译汉&&汉译英"))
        self.lineEdit.setPlaceholderText(_translate("window3", "请输入单词or句子"))
        self.pushButton.setText(_translate("window3", "清空"))
        self.pushButton_2.setText(_translate("window3", "查询"))
        self.label.setText(_translate("window3", "结果："))
        self.comboBox.setItemText(0, _translate("window3", "有道翻译"))
        self.comboBox.setItemText(1, _translate("window3", "百度翻译"))
        self.labelSource.setText(_translate("window3", "选择来源："))
        self.pushButton_3.setText(_translate("window3", "收藏"))

